-- ============================================================
-- Spinning Mill IoT Worker Patrol Monitoring System
-- Unified Patrol Beacon v2 & Wristband v3 Schema
-- ============================================================

-- ------------------------------------------------------------
-- 1. TELEMETRY LOGS TABLE (Historical Events)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.telemetry_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    station_id TEXT NOT NULL,
    target_device TEXT NOT NULL,
    event TEXT NOT NULL,
    lap_duration_sec NUMERIC(10, 2) DEFAULT 0.00,
    signal_rssi INT NOT NULL,
    est_distance_cm NUMERIC(10, 2) DEFAULT 0.00,
    uptime_ms BIGINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_telemetry_station_device 
ON public.telemetry_logs (station_id, target_device, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_telemetry_device_time
ON public.telemetry_logs (target_device, created_at DESC);

-- ------------------------------------------------------------
-- 2. WORKERS TABLE (Live Real-Time Dashboard State)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.workers (
    worker_id TEXT PRIMARY KEY,
    device_id TEXT NOT NULL,
    band_status TEXT DEFAULT 'offline',
    current_zone TEXT DEFAULT 'Side A',
    last_beacon_id TEXT DEFAULT 'M1-A1',
    beacon_rssi INT DEFAULT -70,
    current_machine TEXT DEFAULT 'M1',
    lap_count INT DEFAULT 0,
    lap_duration_sec NUMERIC(10, 2) DEFAULT 0.00,
    lap_started_at TIMESTAMPTZ,
    half_round_done BOOLEAN DEFAULT FALSE,
    directional_heading TEXT DEFAULT 'Stationary',
    motion_state TEXT DEFAULT 'stationary',
    idle_duration_sec INT DEFAULT 0,
    walking_speed_ms NUMERIC(4, 2) DEFAULT 0.00,
    shift_status TEXT DEFAULT 'active',
    incident_type TEXT DEFAULT 'none',
    assistance_request_flag BOOLEAN DEFAULT FALSE,
    wristband_battery_pct INT DEFAULT 100,
    beacon_battery_pct INT DEFAULT 100,
    last_seen TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure unique device_id so beacons can update by device_id
CREATE UNIQUE INDEX IF NOT EXISTS uq_workers_device_id
ON public.workers (device_id);

ALTER TABLE public.workers REPLICA IDENTITY FULL;

-- Ensure numeric precision and columns exist if updating an existing table
ALTER TABLE IF EXISTS public.workers 
    ADD COLUMN IF NOT EXISTS band_status TEXT DEFAULT 'offline',
    ADD COLUMN IF NOT EXISTS lap_started_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS half_round_done BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS last_seen TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE IF EXISTS public.workers 
    ALTER COLUMN lap_duration_sec TYPE NUMERIC(10, 2);

-- Seed default workers
INSERT INTO public.workers (
    worker_id, device_id, current_zone, last_beacon_id, current_machine, lap_count, shift_status
) VALUES 
    ('worker_1', 'WRISTBAND_01', 'Side A', 'M1-A1', 'M1', 0, 'active'),
    ('worker_2', 'WRISTBAND_02', 'Side A', 'M2-A1', 'M2', 0, 'active'),
    ('worker_3', 'WRISTBAND_03', 'Side A', 'M3-A1', 'M3', 0, 'active')
ON CONFLICT (worker_id) DO UPDATE 
SET updated_at = NOW();

-- ------------------------------------------------------------
-- 3. BEACONS TABLE (Station Hardware Catalog & Peer Range)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.beacons (
    beacon_id TEXT PRIMARY KEY,
    station_id TEXT NOT NULL,
    machine_id TEXT NOT NULL,
    zone TEXT NOT NULL,
    status TEXT DEFAULT 'online',
    battery_pct INT DEFAULT 100,
    peer_beacon_id TEXT,
    peer_rssi INT,
    peer_distance_cm NUMERIC(10, 1),
    last_seen TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.beacons REPLICA IDENTITY FULL;

-- Ensure peer columns exist if updating an existing table
ALTER TABLE IF EXISTS public.beacons 
    ADD COLUMN IF NOT EXISTS peer_beacon_id TEXT,
    ADD COLUMN IF NOT EXISTS peer_rssi INT,
    ADD COLUMN IF NOT EXISTS peer_distance_cm NUMERIC(10, 1);

-- Seed Spinning Mill Beacons Grid (M1-A1 & M1-B4 active, rest initialized)
INSERT INTO public.beacons (beacon_id, station_id, machine_id, zone, status)
VALUES 
    -- Machine 1 (M1) Beacons
    ('M1-A1', 'A1', 'M1', 'Side A', 'online'),
    ('M1-A2', 'A2', 'M1', 'Side A', 'offline'),
    ('M1-A3', 'A3', 'M1', 'Side A', 'offline'),
    ('M1-A4', 'A4', 'M1', 'Side A', 'offline'),
    ('M1-B1', 'B1', 'M1', 'Side B', 'offline'),
    ('M1-B2', 'B2', 'M1', 'Side B', 'offline'),
    ('M1-B3', 'B3', 'M1', 'Side B', 'offline'),
    ('M1-B4', 'B4', 'M1', 'Side B', 'online'),

    -- Machine 2 (M2) Beacons
    ('M2-A1', 'A1', 'M2', 'Side A', 'offline'),
    ('M2-A2', 'A2', 'M2', 'Side A', 'offline'),
    ('M2-A3', 'A3', 'M2', 'Side A', 'offline'),
    ('M2-A4', 'A4', 'M2', 'Side A', 'offline'),
    ('M2-B1', 'B1', 'M2', 'Side B', 'offline'),
    ('M2-B2', 'B2', 'M2', 'Side B', 'offline'),
    ('M2-B3', 'B3', 'M2', 'Side B', 'offline'),
    ('M2-B4', 'B4', 'M2', 'Side B', 'offline'),

    -- Machine 3 (M3) Beacons
    ('M3-A1', 'A1', 'M3', 'Side A', 'offline'),
    ('M3-A2', 'A2', 'M3', 'Side A', 'offline'),
    ('M3-A3', 'A3', 'M3', 'Side A', 'offline'),
    ('M3-A4', 'A4', 'M3', 'Side A', 'offline'),
    ('M3-B1', 'B1', 'M3', 'Side B', 'offline'),
    ('M3-B2', 'B2', 'M3', 'Side B', 'offline'),
    ('M3-B3', 'B3', 'M3', 'Side B', 'offline'),
    ('M3-B4', 'B4', 'M3', 'Side B', 'offline')
ON CONFLICT (beacon_id) DO UPDATE 
SET updated_at = NOW();

-- Set non-physical beacons to offline
UPDATE public.beacons
SET status = 'offline'
WHERE beacon_id NOT IN ('M1-A1', 'M1-B4');

-- ------------------------------------------------------------
-- 4. AUTOMATIC TIMESTAMP & PATROL TRIGGER FUNCTIONS
-- ------------------------------------------------------------
-- Beacon heartbeat trigger: only an online heartbeat refreshes last_seen
CREATE OR REPLACE FUNCTION update_beacon_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    IF NEW.status = 'online' THEN
        NEW.last_seen = NOW();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_beacons_updated_at ON public.beacons;
CREATE TRIGGER update_beacons_updated_at
BEFORE UPDATE ON public.beacons
FOR EACH ROW
EXECUTE FUNCTION update_beacon_timestamp();

-- Worker live state trigger: refreshes last_seen when band is active
CREATE OR REPLACE FUNCTION update_worker_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    IF NEW.band_status = 'online' OR NEW.shift_status = 'active' THEN
        NEW.last_seen = NOW();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_workers_updated_at ON public.workers;
CREATE TRIGGER update_workers_updated_at
BEFORE UPDATE ON public.workers
FOR EACH ROW
EXECUTE FUNCTION update_worker_timestamp();

-- 5. Automated Patrol Engine (Converts 'TOUCH' into lap milestones & heading)
CREATE OR REPLACE FUNCTION apply_patrol_event()
RETURNS TRIGGER AS $$
DECLARE
    w public.workers%ROWTYPE;
BEGIN
    IF NEW.event <> 'TOUCH' THEN
        RETURN NEW;
    END IF;

    SELECT * INTO w FROM public.workers
    WHERE device_id = NEW.target_device
    FOR UPDATE;

    IF NOT FOUND THEN
        RETURN NEW;
    END IF;

    IF NEW.station_id = 'M1-A1' THEN
        IF w.lap_started_at IS NULL OR (NOW() - w.lap_started_at > INTERVAL '30 minutes') THEN
            -- First touch at Gateway A1 or stale lap timeout: Patrol round starts
            NEW.event := 'PATROL_STARTED';
            NEW.lap_duration_sec := 0.00;
            UPDATE public.workers
            SET lap_started_at = NOW(),
                half_round_done = FALSE,
                directional_heading = 'Forward',
                last_seen = NOW()
            WHERE worker_id = w.worker_id;

        ELSIF w.half_round_done THEN
            -- Return to Gateway A1 after Midpoint B4: Full round completed!
            NEW.event := 'ROUND_COMPLETED';
            NEW.lap_duration_sec := ROUND(EXTRACT(EPOCH FROM (NOW() - w.lap_started_at))::numeric, 2);
            UPDATE public.workers
            SET lap_count = COALESCE(lap_count, 0) + 1,
                lap_duration_sec = NEW.lap_duration_sec,
                lap_started_at = NOW(),
                half_round_done = FALSE,
                directional_heading = 'Forward',
                last_seen = NOW()
            WHERE worker_id = w.worker_id;

        ELSE
            -- Touched A1 again before reaching B4: Ignore for lap counting
            NEW.event := 'REPEAT_TOUCH';
            NEW.lap_duration_sec := 0.00;
        END IF;

    ELSIF NEW.station_id = 'M1-B4' THEN
        IF w.lap_started_at IS NOT NULL AND NOT w.half_round_done THEN
            -- Touch at Midpoint B4: Half-round completed, heading flipped to Return
            NEW.event := 'HALF_ROUND_COMPLETED';
            NEW.lap_duration_sec := ROUND(EXTRACT(EPOCH FROM (NOW() - w.lap_started_at))::numeric, 2);
            UPDATE public.workers
            SET half_round_done = TRUE,
                directional_heading = 'Return',
                last_seen = NOW()
            WHERE worker_id = w.worker_id;
        ELSE
            NEW.event := 'REPEAT_TOUCH';
            NEW.lap_duration_sec := 0.00;
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_apply_patrol_event ON public.telemetry_logs;
CREATE TRIGGER trg_apply_patrol_event
BEFORE INSERT ON public.telemetry_logs
FOR EACH ROW
EXECUTE FUNCTION apply_patrol_event();

-- ------------------------------------------------------------
-- 6. ROW LEVEL SECURITY (RLS) & PUBLIC ACCESS POLICIES
-- ------------------------------------------------------------
ALTER TABLE public.telemetry_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.beacons ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public select on telemetry_logs" ON public.telemetry_logs;
CREATE POLICY "Allow public select on telemetry_logs" ON public.telemetry_logs FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow public insert on telemetry_logs" ON public.telemetry_logs;
CREATE POLICY "Allow public insert on telemetry_logs" ON public.telemetry_logs FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public select on workers" ON public.workers;
CREATE POLICY "Allow public select on workers" ON public.workers FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow public insert on workers" ON public.workers;
CREATE POLICY "Allow public insert on workers" ON public.workers FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow public update on workers" ON public.workers;
CREATE POLICY "Allow public update on workers" ON public.workers FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public select on beacons" ON public.beacons;
CREATE POLICY "Allow public select on beacons" ON public.beacons FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow public insert on beacons" ON public.beacons;
CREATE POLICY "Allow public insert on beacons" ON public.beacons FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow public update on beacons" ON public.beacons;
CREATE POLICY "Allow public update on beacons" ON public.beacons FOR UPDATE USING (true);

-- ------------------------------------------------------------
-- 7. ENABLE REALTIME PUBLICATIONS
-- ------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
      AND schemaname = 'public' 
      AND tablename = 'workers'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.workers;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
      AND schemaname = 'public' 
      AND tablename = 'telemetry_logs'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.telemetry_logs;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
      AND schemaname = 'public' 
      AND tablename = 'beacons'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.beacons;
  END IF;
END $$;

-- ------------------------------------------------------------
-- 8. UNIVERSAL BEACON FIRMWARE SYNC PATCH (Safe to Re-Run)
-- ------------------------------------------------------------
ALTER TABLE IF EXISTS public.telemetry_logs
    ADD COLUMN IF NOT EXISTS station_id TEXT,
    ADD COLUMN IF NOT EXISTS target_device TEXT,
    ADD COLUMN IF NOT EXISTS event TEXT,
    ADD COLUMN IF NOT EXISTS lap_duration_sec NUMERIC(10, 2) DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS signal_rssi INT,
    ADD COLUMN IF NOT EXISTS est_distance_cm NUMERIC(10, 2) DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS uptime_ms BIGINT DEFAULT 0;

ALTER TABLE IF EXISTS public.workers
    ADD COLUMN IF NOT EXISTS current_zone TEXT DEFAULT 'Side A',
    ADD COLUMN IF NOT EXISTS last_beacon_id TEXT DEFAULT 'M1-A1',
    ADD COLUMN IF NOT EXISTS beacon_rssi INT DEFAULT -70,
    ADD COLUMN IF NOT EXISTS current_machine TEXT DEFAULT 'M1',
    ADD COLUMN IF NOT EXISTS directional_heading TEXT DEFAULT 'Stationary',
    ADD COLUMN IF NOT EXISTS motion_state TEXT DEFAULT 'stationary',
    ADD COLUMN IF NOT EXISTS idle_duration_sec INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS walking_speed_ms NUMERIC(4, 2) DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS shift_status TEXT DEFAULT 'active',
    ADD COLUMN IF NOT EXISTS beacon_battery_pct INT DEFAULT 100,
    ADD COLUMN IF NOT EXISTS lap_count INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS lap_duration_sec NUMERIC(10, 2) DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS last_seen TIMESTAMPTZ DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE IF EXISTS public.beacons
    ADD COLUMN IF NOT EXISTS peer_beacon_id TEXT,
    ADD COLUMN IF NOT EXISTS peer_rssi INT,
    ADD COLUMN IF NOT EXISTS peer_distance_cm NUMERIC(10, 1),
    ADD COLUMN IF NOT EXISTS last_seen TIMESTAMPTZ DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

