-- ============================================================
-- Spinning Mill IoT Worker Patrol Monitoring System
-- Complete Schema with Beacons & 1-Second Real-Time Engine
-- ============================================================

-- 1. Create Telemetry Logs Table (Stores touch events & check-ins)
CREATE TABLE IF NOT EXISTS public.telemetry_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    station_id TEXT NOT NULL,
    target_device TEXT NOT NULL,
    event TEXT NOT NULL,
    lap_duration_sec NUMERIC(10, 2) DEFAULT 0.00,
    signal_rssi INT NOT NULL,
    est_distance_cm NUMERIC(10, 2) DEFAULT 0.00,
    uptime_ms BIGINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_telemetry_station_device 
ON public.telemetry_logs (station_id, target_device, created_at DESC);

-- 2. Create Workers Table (Stores live status & position for dashboard)
CREATE TABLE IF NOT EXISTS public.workers (
    worker_id TEXT PRIMARY KEY,
    device_id TEXT NOT NULL,
    current_zone TEXT DEFAULT 'Side A',
    last_beacon_id TEXT DEFAULT 'M1-A1',
    beacon_rssi INT DEFAULT -70,
    current_machine TEXT DEFAULT 'M1',
    lap_count INT DEFAULT 0,
    lap_duration_sec NUMERIC(10, 2) DEFAULT 0.00,
    directional_heading TEXT DEFAULT 'Forward',
    motion_state TEXT DEFAULT 'walking',
    idle_duration_sec INT DEFAULT 0,
    walking_speed_ms NUMERIC(4, 2) DEFAULT 1.20,
    shift_status TEXT DEFAULT 'active',
    incident_type TEXT DEFAULT 'none',
    assistance_request_flag BOOLEAN DEFAULT FALSE,
    wristband_battery_pct INT DEFAULT 100,
    beacon_battery_pct INT DEFAULT 100,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure lap_duration_sec is NUMERIC(10,2) if table already existed with integer
ALTER TABLE IF EXISTS public.workers 
    ALTER COLUMN lap_duration_sec TYPE NUMERIC(10, 2);

-- Set Replica Identity to FULL so realtime listeners receive the entire row on updates
ALTER TABLE public.workers REPLICA IDENTITY FULL;

-- Seed initial worker
INSERT INTO public.workers (worker_id, device_id, current_zone, last_beacon_id, current_machine, lap_count)
VALUES ('worker_1', 'WRISTBAND_01', 'Side A', 'M1-A1', 'M1', 0)
ON CONFLICT (worker_id) DO NOTHING;

-- 3. Create Beacons Table (For the "DETECTED BEACONS" Card)
CREATE TABLE IF NOT EXISTS public.beacons (
    beacon_id TEXT PRIMARY KEY,
    station_id TEXT NOT NULL,
    machine_id TEXT DEFAULT 'M1',
    zone TEXT DEFAULT 'Side A',
    status TEXT DEFAULT 'online',
    battery_pct INT DEFAULT 100,
    last_seen TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Set Replica Identity to FULL for beacons
ALTER TABLE public.beacons REPLICA IDENTITY FULL;

-- Seed initial beacons
INSERT INTO public.beacons (beacon_id, station_id, machine_id, zone, status)
VALUES 
    ('M1-A1', 'A1', 'M1', 'Side A', 'online'),
    ('M1-B4', 'B4', 'M1', 'Side B', 'online')
ON CONFLICT (beacon_id) DO UPDATE 
SET status = 'online', last_seen = NOW(), updated_at = NOW();

-- 4. Automatic updated_at trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_workers_updated_at ON public.workers;
CREATE TRIGGER update_workers_updated_at
BEFORE UPDATE ON public.workers
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_beacons_updated_at ON public.beacons;
CREATE TRIGGER update_beacons_updated_at
BEFORE UPDATE ON public.beacons
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- 5. Enable Row Level Security (RLS) & Public Dev Policies
ALTER TABLE public.telemetry_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.beacons ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public select on telemetry_logs" ON public.telemetry_logs;
CREATE POLICY "Allow public select on telemetry_logs" ON public.telemetry_logs FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow public insert on telemetry_logs" ON public.telemetry_logs;
CREATE POLICY "Allow public insert on telemetry_logs" ON public.telemetry_logs FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public select on workers" ON public.workers;
CREATE POLICY "Allow public select on workers" ON public.workers FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow public insert on workers" ON public.workers;
CREATE POLICY "Allow public insert on workers" ON public.workers FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow public update on workers" ON public.workers;
CREATE POLICY "Allow public update on workers" ON public.workers FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public select on beacons" ON public.beacons;
CREATE POLICY "Allow public select on beacons" ON public.beacons FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow public insert on beacons" ON public.beacons;
CREATE POLICY "Allow public insert on beacons" ON public.beacons FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow public update on beacons" ON public.beacons;
CREATE POLICY "Allow public update on beacons" ON public.beacons FOR UPDATE USING (true);

-- 6. Enable Realtime Publications
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
      AND schemaname = 'public' 
      AND tablename = 'workers'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.workers;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
      AND schemaname = 'public' 
      AND tablename = 'telemetry_logs'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.telemetry_logs;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
      AND schemaname = 'public' 
      AND tablename = 'beacons'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.beacons;
  END IF;
END $$;
