-- ============================================================
-- Spinning Mill IoT Worker Patrol Monitoring System
-- Supabase PostgreSQL Idempotent Schema Definition
-- ============================================================

-- 1. Historical Telemetry Logs Table
CREATE TABLE IF NOT EXISTS public.telemetry_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    station_id TEXT NOT NULL,
    target_device TEXT NOT NULL,
    event TEXT NOT NULL,
    lap_duration_sec NUMERIC(10, 2) DEFAULT 0.00,
    signal_rssi INT NOT NULL,
    est_distance_cm NUMERIC(10, 2) DEFAULT 0.00,
    uptime_ms BIGINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_telemetry_station_device 
ON public.telemetry_logs (station_id, target_device, created_at DESC);

-- 2. Live Workers Table (For Real-Time Dashboard)
CREATE TABLE IF NOT EXISTS public.workers (
    worker_id TEXT PRIMARY KEY,
    device_id TEXT NOT NULL,
    current_zone TEXT DEFAULT 'Side A',
    last_beacon_id TEXT DEFAULT 'M1-A1',
    beacon_rssi INT DEFAULT -70,
    current_machine TEXT DEFAULT 'M1',
    lap_count INT DEFAULT 0,
    lap_duration_sec NUMERIC(10, 2) DEFAULT 0.00,
    directional_heading TEXT DEFAULT 'Stationary',
    motion_state TEXT DEFAULT 'stationary',
    idle_duration_sec INT DEFAULT 0,
    walking_speed_ms NUMERIC(4, 2) DEFAULT 0.00,
    shift_status TEXT DEFAULT 'login',
    incident_type TEXT DEFAULT 'none',
    assistance_request_flag BOOLEAN DEFAULT FALSE,
    wristband_battery_pct INT DEFAULT 100,
    beacon_battery_pct INT DEFAULT 100,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed initial record
INSERT INTO public.workers (worker_id, device_id, current_zone, last_beacon_id, current_machine, lap_count)
VALUES ('worker_1', 'WRISTBAND_01', 'Side A', 'M1-A1', 'M1', 0)
ON CONFLICT (worker_id) DO NOTHING;

-- 3. Automatic updated_at Trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_workers_updated_at ON public.workers;
CREATE TRIGGER update_workers_updated_at
BEFORE UPDATE ON public.workers
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- 4. Enable Row Level Security (RLS) & Public Dev Policies
ALTER TABLE public.telemetry_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public select on telemetry_logs" ON public.telemetry_logs;
CREATE POLICY "Allow public select on telemetry_logs" ON public.telemetry_logs FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert on telemetry_logs" ON public.telemetry_logs;
CREATE POLICY "Allow public insert on telemetry_logs" ON public.telemetry_logs FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public select on workers" ON public.workers;
CREATE POLICY "Allow public select on workers" ON public.workers FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert on workers" ON public.workers;
CREATE POLICY "Allow public insert on workers" ON public.workers FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update on workers" ON public.workers;
CREATE POLICY "Allow public update on workers" ON public.workers FOR UPDATE USING (true);

-- 5. Enable Realtime Publications
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
      AND schemaname = 'public' 
      AND tablename = 'workers'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.workers;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
      AND schemaname = 'public' 
      AND tablename = 'telemetry_logs'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.telemetry_logs;
  END IF;
END $$;
